# Generated by Django 6.1.1 on 2026-09-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rumour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('current_club', models.CharField(max_length=100)),
                ('linked_club', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=200)),
                ('reliability', models.IntegerField(default=50)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
