# Generated by Django 6.1.1 on 2026-09-06 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('current_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfers.club')),
            ],
        ),
        migrations.CreateModel(
            name='TransferRumour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('probability', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_rumours', to='transfers.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfers.player')),
                ('to_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_rumours', to='transfers.club')),
            ],
        ),
    ]
