# Generated by Django 6.1.1 on 2026-09-22 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_source_source_type'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferrumour',
            name='player',
        ),
        migrations.AlterField(
            model_name='transferrumour',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rumours', to='news.source'),
        ),
        migrations.CreateModel(
            name='TransferClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_claims', to='transfers.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfers.player')),
            ],
        ),
        migrations.AddField(
            model_name='transferrumour',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rumours', to='transfers.transferclaim'),
        ),
    ]
