# Generated by Django 6.1.1 on 2026-09-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_remove_transferrumour_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrumour',
            name='transfer_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
