# Generated by Django 6.1.1 on 2026-09-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_transferrumour_transfer_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrumour',
            name='article_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='transferrumour',
            name='article_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferrumour',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
