# Generated by Django 6.1.1 on 2026-09-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_transferrumour_article_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrumour',
            name='evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferrumour',
            name='article_url',
            field=models.URLField(unique=True),
        ),
    ]
