# Generated by Django 6.1.1 on 2026-09-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_transferrumour_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferclaim',
            name='reliability_score',
            field=models.FloatField(default=0.0),
        ),
    ]
