# Generated by Django 6.1.1 on 2026-09-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('initial_reliability', models.FloatField(default=50.0)),
                ('total_rumours', models.IntegerField(default=0)),
                ('confirmed_rumours', models.IntegerField(default=0)),
                ('failed_rumours', models.IntegerField(default=0)),
                ('reliability_score', models.FloatField(default=50.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
