# Generated by Django 6.1.1 on 2026-09-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('MEDIA', 'Media'), ('JOURNALIST', 'Journalist'), ('OFFICIAL', 'Official')], default='MEDIA', max_length=20),
        ),
    ]
